### ISSUE TITLE
Prefix collision with CloudKit framework

### ISSUE THREAD

**Issue by vmartinelli** [CameraKit/camerakit-ios#10]
Hello. Thank you for the initiative to bring this framework for all developers. :)

I'm afraid, however, with the class name prefix you choose, that could be collisions with Apple's CloudKit framework.

Apple suggests that ObjC "safe" prefixes use 3 letters and not only 2 (two letters prefixes would be reserved for Apple use only).

In Swift prefixes are not usually required, so they can be removed and only specified for ObjC compatibility purposes.

I'd suggest using something like `CKF` ("CameraKitFramework") as prefix while in ObjC (`CKFSession`, for example). And something like `CameraSession`, for example, while using it in Swift.

**Comment by adrianmateoaea24** [comment]
Thank you for contributing to CameraKit! 🙌
Agree, we will find a better naming scheme but most likely keep the prefix due to our ObjC support.

**Comment by austinkettner** [comment]
Dig the `CKF` prefix alternative, we will probably use that, thanks @vmartinelli!
