### ISSUE TITLE
Broken preview in landscape

### ISSUE THREAD

**Issue by igorkulman** [CameraKit/camerakit-ios#7]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](CONTRIBUTING.md)?

There is no such file

### Environment

CameraKit Version:

0.1

iOS Device:

iPhone 6S

iOS Version:

12.1.4

### Steps to Reproduce

1. Include the component in your app or change the Demo app to support landscape
2. Rotate the device to landscape

### Expected Behavior

The preview should show what the camera sees in landscape

### Actual Behavior

Preview showing zoomed picture rotated 90 degrees

### Reproducible Demo

This project, the demo when allowing landscape

**Comment by adrianmateoaea24** [comment]
Thank you for contributing to CameraKit by submitting this bug report! 👍
We will consider it and resolve it in our next stable release 😄

**Comment by igorkulman** [comment]
Funny to see such generic corporate reply on Github.. twice :)

**Comment by austinkettner** [comment]
lol fair point @igorkulman
