### ISSUE TITLE
Landscape photo always saved as portrait

### ISSUE THREAD

**Issue by igorkulman** [CameraKit/camerakit-ios#8]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](CONTRIBUTING.md)?

No such file

### Environment

CameraKit Version:

0.1

iOS Device:

iPhone 6S

iOS Version:

12.1.4

### Steps to Reproduce

(Write your steps here:)

1. Rotate the device to landscape
2. Take a photo
3. Save the photo

### Expected Behavior

Photon saved as landscape

### Actual Behavior

Photo saved as portrait

### Reproducible Demo

Demo in this repo

**Comment by adrianmateoaea24** [comment]
Thank you for contributing to CameraKit by submitting this bug report! 👍
We will consider it and resolve it in our next stable release 😄
